-- oushodhwala schema expansions (run on XAMPP / cPanel MySQL)
USE oushodhwala_db;

CREATE TABLE IF NOT EXISTS offers (
  id VARCHAR(36) PRIMARY KEY,
  code VARCHAR(50) NOT NULL UNIQUE,
  title VARCHAR(255) NOT NULL,
  subtitle TEXT,
  discount_pct DECIMAL(5,2) DEFAULT 0.00,
  max_discount DECIMAL(12,2),
  min_order DECIMAL(12,2) DEFAULT 0.00,
  expires_at TIMESTAMP NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS suppliers (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  phone VARCHAR(50),
  email VARCHAR(150),
  address TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS purchase_orders (
  id VARCHAR(36) PRIMARY KEY,
  po_number VARCHAR(100) NOT NULL UNIQUE,
  supplier_id VARCHAR(36) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'draft',
  total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  notes TEXT,
  created_by VARCHAR(36),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS expenses (
  id VARCHAR(36) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  category VARCHAR(100),
  spent_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  note TEXT,
  created_by VARCHAR(36),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stock_transfers (
  id VARCHAR(36) PRIMARY KEY,
  from_branch_id VARCHAR(36) NOT NULL,
  to_branch_id VARCHAR(36) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'pending',
  notes TEXT,
  created_by VARCHAR(36),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS media_assets (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  path TEXT NOT NULL,
  url TEXT NOT NULL,
  mime_type VARCHAR(100),
  size INT DEFAULT 0,
  created_by VARCHAR(36),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS app_settings (
  id VARCHAR(36) PRIMARY KEY,
  `key` VARCHAR(100) NOT NULL UNIQUE,
  value TEXT,
  label VARCHAR(255),
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS campaigns (
  id VARCHAR(36) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  channel VARCHAR(50) DEFAULT 'sms',
  body TEXT,
  status VARCHAR(50) NOT NULL DEFAULT 'draft',
  scheduled_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS support_conversations (
  id VARCHAR(36) PRIMARY KEY,
  user_id VARCHAR(36) NOT NULL,
  title VARCHAR(255) DEFAULT 'Support',
  status VARCHAR(50) NOT NULL DEFAULT 'open',
  agent_active BOOLEAN NOT NULL DEFAULT FALSE,
  agent_name VARCHAR(150),
  agent_last_seen TIMESTAMP NULL,
  last_message_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  unread_for_agent INT NOT NULL DEFAULT 0,
  unread_for_user INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS support_messages (
  id VARCHAR(36) PRIMARY KEY,
  conversation_id VARCHAR(36) NOT NULL,
  sender VARCHAR(20) NOT NULL,
  body TEXT NOT NULL,
  agent_name VARCHAR(150),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX (conversation_id)
);

CREATE TABLE IF NOT EXISTS notifications (
  id VARCHAR(36) PRIMARY KEY,
  user_id VARCHAR(36) NOT NULL,
  kind VARCHAR(50) NOT NULL DEFAULT 'system',
  title VARCHAR(255) NOT NULL,
  body TEXT,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX (user_id)
);

CREATE TABLE IF NOT EXISTS user_favorites (
  id VARCHAR(36) PRIMARY KEY,
  user_id VARCHAR(36) NOT NULL,
  product_id VARCHAR(36) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  reminder_config JSON,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_fav (user_id, product_id)
);

CREATE TABLE IF NOT EXISTS user_recent_medicines (
  id VARCHAR(36) PRIMARY KEY,
  user_id VARCHAR(36) NOT NULL,
  product_id VARCHAR(36) NOT NULL,
  last_viewed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_recent (user_id, product_id)
);

CREATE TABLE IF NOT EXISTS prescription_shares (
  id VARCHAR(36) PRIMARY KEY,
  prescription_id VARCHAR(36) NOT NULL,
  user_id VARCHAR(36) NOT NULL,
  token VARCHAR(64) NOT NULL UNIQUE,
  scopes JSON,
  expires_at TIMESTAMP NOT NULL,
  revoked BOOLEAN NOT NULL DEFAULT FALSE,
  views INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rx_retention (
  id VARCHAR(36) PRIMARY KEY,
  user_id VARCHAR(36) NOT NULL UNIQUE,
  days INT NOT NULL DEFAULT 0,
  notify_email BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- ── Remaining RPC schema gaps (admin-rpc Server Actions) ──

ALTER TABLE appointments
  ADD COLUMN IF NOT EXISTS invoice_no VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS refund_status VARCHAR(50) NOT NULL DEFAULT 'none',
  ADD COLUMN IF NOT EXISTS refund_amount DECIMAL(10,2) DEFAULT 0.00;

ALTER TABLE diagnostic_bookings
  ADD COLUMN IF NOT EXISTS user_id VARCHAR(36) NULL,
  ADD COLUMN IF NOT EXISTS booking_no VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS collector_name VARCHAR(150) DEFAULT '',
  ADD COLUMN IF NOT EXISTS collector_phone VARCHAR(50) DEFAULT '',
  ADD COLUMN IF NOT EXISTS payment_method VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS payment_status VARCHAR(50) DEFAULT 'unpaid';

ALTER TABLE service_requests
  ADD COLUMN IF NOT EXISTS service_name VARCHAR(255) DEFAULT '',
  ADD COLUMN IF NOT EXISTS admin_note TEXT NULL,
  ADD COLUMN IF NOT EXISTS payment_status VARCHAR(50) DEFAULT 'unpaid',
  ADD COLUMN IF NOT EXISTS fee DECIMAL(10,2) DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS assignee_name VARCHAR(150) DEFAULT '',
  ADD COLUMN IF NOT EXISTS assignee_phone VARCHAR(50) DEFAULT '';

ALTER TABLE deliveries
  ADD COLUMN IF NOT EXISTS order_no VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS user_id VARCHAR(36) NULL,
  ADD COLUMN IF NOT EXISTS otp VARCHAR(10) NULL,
  ADD COLUMN IF NOT EXISTS public_token VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS token_expires_at TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS token_revoked BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS token_scope VARCHAR(30) DEFAULT 'public';

ALTER TABLE purchase_orders
  ADD COLUMN IF NOT EXISTS supplier_name VARCHAR(150) DEFAULT '',
  ADD COLUMN IF NOT EXISTS expected_at DATE NULL,
  ADD COLUMN IF NOT EXISTS subtotal DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS discount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS received_at TIMESTAMP NULL;

CREATE TABLE IF NOT EXISTS purchase_order_items (
  id VARCHAR(36) PRIMARY KEY,
  po_id VARCHAR(36) NOT NULL,
  product_id VARCHAR(36) NOT NULL,
  product_name VARCHAR(255) NOT NULL DEFAULT '',
  qty INT NOT NULL DEFAULT 0,
  cost DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  batch_no VARCHAR(100) DEFAULT '',
  expiry DATE NULL,
  received_qty INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX (po_id)
);

ALTER TABLE stock_batches
  ADD COLUMN IF NOT EXISTS product_name VARCHAR(255) DEFAULT '',
  ADD COLUMN IF NOT EXISTS supplier_id VARCHAR(36) NULL,
  ADD COLUMN IF NOT EXISTS po_id VARCHAR(36) NULL;

ALTER TABLE stock_alerts
  ADD COLUMN IF NOT EXISTS product_name VARCHAR(255) DEFAULT '',
  ADD COLUMN IF NOT EXISTS ref VARCHAR(150) NULL,
  ADD COLUMN IF NOT EXISTS detail TEXT NULL;

ALTER TABLE notifications
  ADD COLUMN IF NOT EXISTS order_no VARCHAR(100) DEFAULT '';

-- ── Rx-read / AI parse cache (shim removal) ──
ALTER TABLE prescriptions
  ADD COLUMN IF NOT EXISTS guest_token VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS parsed JSON NULL,
  ADD COLUMN IF NOT EXISTS parsed_at TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS parse_note TEXT NULL;

ALTER TABLE prescription_audit
  ADD COLUMN IF NOT EXISTS version INT DEFAULT 1,
  ADD COLUMN IF NOT EXISTS user_id VARCHAR(36) NULL;
