-- yessbgd schema expansions (XAMPP / cPanel MySQL)
USE yessbgd_db;

CREATE TABLE IF NOT EXISTS cms_pages (
  id VARCHAR(36) PRIMARY KEY,
  page VARCHAR(100) NOT NULL,
  section_key VARCHAR(100) NOT NULL,
  sort_order INT DEFAULT 0,
  title TEXT,
  title_bn TEXT,
  subtitle TEXT,
  subtitle_bn TEXT,
  body TEXT,
  body_bn TEXT,
  cta_label VARCHAR(150),
  cta_href VARCHAR(255),
  image_url TEXT,
  data JSON,
  is_published BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX (page)
);

-- Menu / settings / ops columns (safe to re-run on MariaDB 10.3.3+)
ALTER TABLE cms_menu_items
  ADD COLUMN IF NOT EXISTS location VARCHAR(50) NOT NULL DEFAULT 'header',
  ADD COLUMN IF NOT EXISTS group_label VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS is_external BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS is_published BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS depth INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS icon VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS description TEXT NULL,
  ADD COLUMN IF NOT EXISTS description_bn TEXT NULL,
  ADD COLUMN IF NOT EXISTS accent VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS item_style VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS badge VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS badge_bn VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS visible_to VARCHAR(30) DEFAULT 'all';

ALTER TABLE cms_settings
  ADD COLUMN IF NOT EXISTS label VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS `group` VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS sort_order INT DEFAULT 0;

ALTER TABLE cms_ventures ADD COLUMN IF NOT EXISTS is_published BOOLEAN DEFAULT TRUE;
ALTER TABLE cms_services ADD COLUMN IF NOT EXISTS is_published BOOLEAN DEFAULT TRUE;
ALTER TABLE cms_industries ADD COLUMN IF NOT EXISTS is_published BOOLEAN DEFAULT TRUE;

ALTER TABLE contact_messages
  ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'new',
  ADD COLUMN IF NOT EXISTS status_note TEXT NULL,
  ADD COLUMN IF NOT EXISTS status_updated_at TIMESTAMP NULL;

ALTER TABLE job_applications
  ADD COLUMN IF NOT EXISTS status_note TEXT NULL,
  ADD COLUMN IF NOT EXISTS status_updated_at TIMESTAMP NULL;

ALTER TABLE cms_media
  ADD COLUMN IF NOT EXISTS alt_text VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS folder VARCHAR(100) NULL;
