export const STATUS: Record<string, string> = {
  pending: "অপেক্ষমাণ",
  confirmed: "নিশ্চিত হয়েছে",
  processing: "প্রস্তুত হচ্ছে",
  shipped: "পথে আছে",
  delivered: "ডেলিভারি হয়েছে",
  cancelled: "বাতিল",
};

export const DELIVERY_STATUS: Record<string, string> = {
  pending: "অপেক্ষমাণ",
  assigned: "রাইডার নিযুক্ত",
  picked_up: "পিকড আপ",
  out_for_delivery: "ডেলিভারির পথে",
  delivered: "ডেলিভারি সম্পন্ন",
  failed: "ব্যর্থ",
  cancelled: "বাতিল",
};

export const emptyProduct = {
  id: "",
  name: "",
  en: "",
  brand: "",
  generic: "",
  form: "ট্যাবলেট",
  pack: "",
  price: 0,
  mrp: 0,
  category: "medicine",
  rx: false,
  emoji: "💊",
  description: "",
  description_en: "",
  image_url: "",
  medicine_image_url: "",
  manufacturer: "",
  indications: "",
  indications_en: "",
  dosage: "",
  dosage_en: "",
  side_effects: "",
  side_effects_en: "",
  strength: "",
  base_name: "",
  contraindications: "",
  contraindications_en: "",
  pregnancy: "",
  pregnancy_en: "",
  precautions: "",
  precautions_en: "",
  therapeutic_class: "",
  therapeutic_class_en: "",
  storage: "",
  storage_en: "",
  stock: 0,
  low_stock_threshold: 10,
  active: true,
};

export const emptyDoctor = {
  name: "",
  spec: "",
  degree: "",
  exp: "",
  fee: 0,
  emoji: "👨‍⚕️",
  photo_url: "",
  phone: "",
  whatsapp: "",
  video_url: "",
  sort_order: 0,
  work_start: "10:00",
  work_end: "22:00",
  slot_minutes: 30,
  work_days: [0, 1, 2, 3, 4, 5, 6] as number[],
};

export const emptyLab = {
  id: "",
  bn: "",
  en: "",
  price: 0,
  mrp: 0,
  grp: "vital",
  prep: "",
  active: true,
  sort_order: 0,
};
